### ISSUE TITLE
fragmentation mode doesn't work with audio

### ISSUE THREAD

**Issue by rhwu** [lieff/minimp4#13]
Steps to reproduce:
1) Enable ENABLE_AUDIO in minimp4_test.c. Change resolution to 240x160.
2) Build minimp4_test with fdk-aac-2.0.1.
3) Download stream.h264 and stream.pcm from https://github.com/lieff/minirtmp.
4) Run following tests:
./minimp4_x86 -m  stream.h264 stream.mp4
./minimp4_x86 -m -s stream.h264 stream-s.mp4
./minimp4_x86 -m -f stream.h264 stream-f.mp4
5) stream.mp4 and stream-s.mp4 are playable with audio. stream-f.mp4 is not playable.

Can you help to take a look? Thanks!
[stream-f.mp4.zip](https://github.com/lieff/minimp4/files/4210963/stream-f.mp4.zip)

**Comment by lieff** [comment]
Hello :) Thanks for the issue.

I think I see what's going on. It seems all tracks must be included in every moof header, while minimp4 generated separate moof for each track. Will fix it when I can.

**Comment by lieff** [comment]
Here quick fix https://github.com/lieff/minimp4/commit/78f7e1cb6d0acea0c77ad113dd2e045ffec0321c .

**Comment by rhwu** [comment]
Thanks for your quick response!

With 78f7e1c, stream-f.mp4 is still not playable. And the duration seems to be doubled.
[stream-f.mp4.gz](https://github.com/lieff/minimp4/files/4211266/stream-f.mp4.gz)

**Comment by lieff** [comment]
Forgot to update sample count in all cases. I've update the fix https://github.com/lieff/minimp4/commit/590bad98248199be1e21f295964660e9eaaf5d7d

**Comment by lieff** [comment]
Turns out it's not so simple to fix, demuxers tries to demux even when sample_count=0 and reads invalid offsets. Proper fix will be flush moof header with samples when at least one audio and video sample available.

**Comment by lieff** [comment]
Hmm, that's strange. Seems sample_count=0 approach is correct and fix is working, but ffmpeg fails on it because of a bug. Bug is fixed in latest ffmpeg master and https://github.com/lieff/minimp4/commit/f0c5a193f1e4d521f12c80c21d0e7ac3489e9dc8 works with it.

**Comment by lieff** [comment]
Turns out all tracks in moof box not needed too, fix simplified to https://github.com/lieff/minimp4/commit/d61910b2c39a7627bdc8fea35524ced8e4d00f19 . Please check if it works for you.

**Comment by rhwu** [comment]
Thanks a lot for all your effort!

I rerun previous tests, stream-f.mp4 is fine now, but stream.mp4 and stream-s.mp4 no longer has audio.

**Comment by lieff** [comment]
Ah, yes, small correction https://github.com/lieff/minimp4/commit/84aa678931d0e766d6f695166c871c2c61d51b2e .

**Comment by rhwu** [comment]
Works now! Thanks for the fix!

**Comment by lieff** [comment]
Glad to hear :) Closing then, feel free to reopen if it breaks again.
