### ISSUE TITLE
Access Unit Delimiter (AUD) handling

### ISSUE THREAD

**Issue by b71729** [lieff/minimp4#27]
I'm using this library to mux a H.264 bitstream that contains **type 9** NAL units (Access unit delimiter) before each full frame.

According to [Wikipedia](https://en.wikipedia.org/wiki/Network_Abstraction_Layer#Access_Units), the Unit Access Delimiter is used as a basic prefix NAL unit to aid in interpreting frames:

> A set of NAL units in a specified form is referred to as an access unit. The decoding of each access unit results in one decoded picture. Each access unit contains a set of VCL NAL units that together compose a primary coded picture. **It may also be prefixed with an access unit delimiter to aid in locating the start of the access unit.**

The code on master will return an error if it encounters an AUD, whereas it seems to work fine by skipping over the NAL unit. I think this is because it's an optional 'helper' unit that the library does not depend on to correctly interpret the stream.

The code I've experimented with essentially changes a `return err` statement to instead `continue` parsing other NAL units in the buffer:

```C
2343| if (9 == payload_type)
2344|     return err; /* access unit delimiter */
```

```C
2343| if (9 == payload_type)
2344|     continue; /* access unit delimiter */
```

It would be nice not to have to maintain a long lived fork, so I'm submitting this as a way of opening discussion to solutions for handling such streams (as are produced by the built-in Windows H.264 Encoder). More than happy to contribute code.

**Comment by lieff** [comment]
Hi)
Sorry for late reply. This looks like correct change, this code was written before slices support, so 1 frame = 1 nalu was assumed.
Mind make a PR?

**Comment by b71729** [comment]
Thanks @lieff , that's submitted.

**Comment by lieff** [comment]
Thanks) Merged.
