### ISSUE TITLE
is This lib supporting mux fragment mp4？

### ISSUE THREAD

**Issue by myseemylife** [lieff/minimp4#3]

**Comment by lieff** [comment]
If you mean moof atom, which contains small part of the index to allow streaming then no.
But if you are using one mdat per frame mode and there only one stream - then you can you can demux each mdat and assume it as frame without reading the index.

**Comment by myseemylife** [comment]
> If you mean moof atom, which contains small part of the index to allow streaming then no.
> But if you are using one mdat per frame mode and there only one stream - then you can demux each mdat and assume it as frame without reading the index.

in my use case，i have raw h264 frames packed with self define header,and i try to find a c or c++ lib to do  mux things, i'm not familiar with  fragment MP4 format  and mp4.

**Comment by lieff** [comment]
Yeah, for HTML5 we need fMP4/moof atom support. Hack only possible in own demux code.
I think it's not so hard to add such support.

**Comment by myseemylife** [comment]
aha!! After long time searching，i have got libmov ~this lib can mux annex-b h264 or hevc bytes into  Fragment Mp4!

**Comment by lieff** [comment]
Good catch) I've add this lib in readme links too.
