### ISSUE TITLE
Cmd line bug, typos.

### ISSUE THREAD

**Issue by seerdecker** [lieff/minimp4#30]
```
-    int is_hevc = (0 != strstr(argv[1], "265")) || (0 != strstr(argv[i], "hevc"));
+    int is_hevc = (0 != strstr(argv[i], "265")) || (0 != strstr(argv[i], "hevc"));
```

// Second is optonal duration update at beginning of file in fragmenatation mode.
===> Proofread.

Thanks for the project.

**Comment by lieff** [comment]
Hi)
Thanks for catching this) fixed in https://github.com/lieff/minimp4/commit/4575afb4f69ace25a1a048e25cc86bf8c8d14f2b
